export const START_LOAD_ITEM = '@USERS/START_LOAD_ITEM';
export const ADD_ITEM = '@USERS/ADD_ITEM';
export const LOAD_ITEM_ERROR = '@USERS/LOAD_ITEMS_ERROR';

export const START_PUSH_ITEM = '@USER/START_PUSH_ITEM';
export const PUSH_ITEM_ERROR = '@USER/PUSH_ITEM_ERROR';

export const AUTHENTICATE = '@USER/AUTHENTICATE';
